package stu.lcr.eztravel.entity;

import java.io.Serializable;

public class OrderInfo implements Serializable {
    //订单号
    private Integer bookingID;

    // 用户id
    private Integer userID;

    //酒店id
    private Integer hotelID;

    //房型编号
    private Integer roomTypeID;

    // 酒店名称
    private String hotelName;

    //房型名称
    private String roomTypeName;

    // 入住人姓名
    private String fullName;

    // 联系电话
    private String phone;

    //入住日期
    private String checkIn;

    // 退房日期
    private String checkOut;

    // 预订房间数量
    private Integer roomNum;

    // 订单总价
    private Double price;

    // 备注
    private String remark;

    //订单状态(0:已下单. 1:待处理, 2:待入住, 2:待评价,3:完成,4:用户删除，-1:待退款，-2:已退款)
    private Byte bookingStatus;

    // 创建时间
    private String createTime;

    // This field was generated by MyBatis Generator.
    private static final long serialVersionUID = 1L;

    // 获取 订单号 字段:booking_info.bookingID
    public Integer getBookingID() {
        return bookingID;
    }

    // 设置 订单号 字段:booking_info.bookingID
    public void setBookingID(Integer bookingID) {
        this.bookingID = bookingID;
    }

    public Integer getUserID() {
        return userID;
    }

    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    public Integer getHotelID() {
        return hotelID;
    }

    public void setHotelID(Integer hotelID) {
        this.hotelID = hotelID;
    }

    public Integer getRoomTypeID() {
        return roomTypeID;
    }

    public void setRoomTypeID(Integer roomTypeID) {
        this.roomTypeID = roomTypeID;
    }

    public String getHotelName() {
        return hotelName;
    }

    public void setHotelName(String hotelName) {
        this.hotelName = hotelName == null ? null : hotelName.trim();
    }

    public String getRoomTypeName() {
        return roomTypeName;
    }

    public void setRoomTypeName(String roomTypeName) {
        this.roomTypeName = roomTypeName == null ? null : roomTypeName.trim();
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    public String getCheckIn() {
        return checkIn;
    }

    public void setCheckIn(String checkIn) {
        this.checkIn = checkIn;
    }

    public String getCheckOut() {
        return checkOut;
    }

    public void setCheckOut(String checkOut) {
        this.checkOut = checkOut;
    }

    public Integer getRoomNum() {
        return roomNum;
    }

    public void setRoomNum(Integer roomNum) {
        this.roomNum = roomNum;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 获取 订单状态(0:已下单. 1:待处理, 2:待入住, 2:待评价,3:完成,4:用户删除，-1:待退款，-2:已退款) 字段:booking_info.bookingStatus
     */
    public Byte getBookingStatus() {
        return bookingStatus;
    }

    /**
     * 设置 订单状态(0:已下单. 1:待处理, 2:待入住, 2:待评价,3:完成,4:用户删除，-1:待退款，-2:已退款) 字段:booking_info.bookingStatus
     */
    public void setBookingStatus(Byte bookingStatus) {
        this.bookingStatus = bookingStatus;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
}