package cuit.hotel.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class BookingInfo implements Serializable {
    /**
     * 订单号
     * 表字段 : booking_info.bookingID
     */
    private Integer bookingID;

    /**
     * 用户id
     * 表字段 : booking_info.userID
     */
    private Integer userID;

    /**
     * 酒店id
     * 表字段 : booking_info.hotelID
     */
    private Integer hotelID;

    /**
     * 房型编号
     * 表字段 : booking_info.roomTypeID
     */
    private Integer roomTypeID;

    /**
     * 酒店名称
     * 表字段 : booking_info.hotelName
     */
    private String hotelName;

    /**
     * 房型名称
     * 表字段 : booking_info.roomTypeName
     */
    private String roomTypeName;

    /**
     * 入住人姓名
     * 表字段 : booking_info.fullName
     */
    private String fullName;

    /**
     * 联系电话
     * 表字段 : booking_info.phone
     */
    private String phone;

    /**
     * 入住日期
     * 表字段 : booking_info.checkIn
     */
    private String checkIn;

    /**
     * 退房日期
     * 表字段 : booking_info.checkOut
     */
    private String checkOut;

    /**
     * 预订房间数量
     * 表字段 : booking_info.roomNum
     */
    private Integer roomNum;

    /**
     * 订单总价
     * 表字段 : booking_info.price
     */
    private Double price;

    /**
     * 备注
     * 表字段 : booking_info.remark
     */
    private String remark;

    /**
     * 订单状态(0:已下单. 1:待处理, 2:待入住, 2:待评价,3:完成,4:用户删除，-1:待退款，-2:已退款)
     * 表字段 : booking_info.bookingStatus
     */
    private Byte bookingStatus;

    /**
     * 创建时间
     * 表字段 : booking_info.createTime
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table booking_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 订单号 字段:booking_info.bookingID
     *
     * @return booking_info.bookingID, 订单号
     */
    public Integer getBookingID() {
        return bookingID;
    }

    /**
     * 设置 订单号 字段:booking_info.bookingID
     *
     * @param bookingID the value for booking_info.bookingID, 订单号
     */
    public void setBookingID(Integer bookingID) {
        this.bookingID = bookingID;
    }

    /**
     * 获取 用户id 字段:booking_info.userID
     *
     * @return booking_info.userID, 用户id
     */
    public Integer getUserID() {
        return userID;
    }

    /**
     * 设置 用户id 字段:booking_info.userID
     *
     * @param userID the value for booking_info.userID, 用户id
     */
    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    /**
     * 获取 酒店id 字段:booking_info.hotelID
     *
     * @return booking_info.hotelID, 酒店id
     */
    public Integer getHotelID() {
        return hotelID;
    }

    /**
     * 设置 酒店id 字段:booking_info.hotelID
     *
     * @param hotelID the value for booking_info.hotelID, 酒店id
     */
    public void setHotelID(Integer hotelID) {
        this.hotelID = hotelID;
    }

    /**
     * 获取 房型编号 字段:booking_info.roomTypeID
     *
     * @return booking_info.roomTypeID, 房型编号
     */
    public Integer getRoomTypeID() {
        return roomTypeID;
    }

    /**
     * 设置 房型编号 字段:booking_info.roomTypeID
     *
     * @param roomTypeID the value for booking_info.roomTypeID, 房型编号
     */
    public void setRoomTypeID(Integer roomTypeID) {
        this.roomTypeID = roomTypeID;
    }

    /**
     * 获取 酒店名称 字段:booking_info.hotelName
     *
     * @return booking_info.hotelName, 酒店名称
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * 设置 酒店名称 字段:booking_info.hotelName
     *
     * @param hotelName the value for booking_info.hotelName, 酒店名称
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName == null ? null : hotelName.trim();
    }

    /**
     * 获取 房型名称 字段:booking_info.roomTypeName
     *
     * @return booking_info.roomTypeName, 房型名称
     */
    public String getRoomTypeName() {
        return roomTypeName;
    }

    /**
     * 设置 房型名称 字段:booking_info.roomTypeName
     *
     * @param roomTypeName the value for booking_info.roomTypeName, 房型名称
     */
    public void setRoomTypeName(String roomTypeName) {
        this.roomTypeName = roomTypeName == null ? null : roomTypeName.trim();
    }

    /**
     * 获取 入住人姓名 字段:booking_info.fullName
     *
     * @return booking_info.fullName, 入住人姓名
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * 设置 入住人姓名 字段:booking_info.fullName
     *
     * @param fullName the value for booking_info.fullName, 入住人姓名
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * 获取 联系电话 字段:booking_info.phone
     *
     * @return booking_info.phone, 联系电话
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置 联系电话 字段:booking_info.phone
     *
     * @param phone the value for booking_info.phone, 联系电话
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 获取 入住日期 字段:booking_info.checkIn
     *
     * @return booking_info.checkIn, 入住日期
     */
    public String getCheckIn() {
        return checkIn;
    }

    /**
     * 设置 入住日期 字段:booking_info.checkIn
     *
     * @param checkIn the value for booking_info.checkIn, 入住日期
     */
    public void setCheckIn(String checkIn) {
        this.checkIn = checkIn;
    }

    /**
     * 获取 退房日期 字段:booking_info.checkOut
     *
     * @return booking_info.checkOut, 退房日期
     */
    public String getCheckOut() {
        return checkOut;
    }

    /**
     * 设置 退房日期 字段:booking_info.checkOut
     *
     * @param checkOut the value for booking_info.checkOut, 退房日期
     */
    public void setCheckOut(String checkOut) {
        this.checkOut = checkOut;
    }

    /**
     * 获取 预订房间数量 字段:booking_info.roomNum
     *
     * @return booking_info.roomNum, 预订房间数量
     */
    public Integer getRoomNum() {
        return roomNum;
    }

    /**
     * 设置 预订房间数量 字段:booking_info.roomNum
     *
     * @param roomNum the value for booking_info.roomNum, 预订房间数量
     */
    public void setRoomNum(Integer roomNum) {
        this.roomNum = roomNum;
    }

    /**
     * 获取 订单总价 字段:booking_info.price
     *
     * @return booking_info.price, 订单总价
     */
    public Double getPrice() {
        return price;
    }

    /**
     * 设置 订单总价 字段:booking_info.price
     *
     * @param price the value for booking_info.price, 订单总价
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * 获取 备注 字段:booking_info.remark
     *
     * @return booking_info.remark, 备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置 备注 字段:booking_info.remark
     *
     * @param remark the value for booking_info.remark, 备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 获取 订单状态(0:已下单. 1:待处理, 2:待入住, 2:待评价,3:完成,4:用户删除，-1:待退款，-2:已退款) 字段:booking_info.bookingStatus
     *
     * @return booking_info.bookingStatus, 订单状态(0:已下单. 1:待处理, 2:待入住, 2:待评价,3:完成,4:用户删除，-1:待退款，-2:已退款)
     */
    public Byte getBookingStatus() {
        return bookingStatus;
    }

    /**
     * 设置 订单状态(0:已下单. 1:待处理, 2:待入住, 2:待评价,3:完成,4:用户删除，-1:待退款，-2:已退款) 字段:booking_info.bookingStatus
     *
     * @param bookingStatus the value for booking_info.bookingStatus, 订单状态(0:已下单. 1:待处理, 2:待入住, 2:待评价,3:完成,4:用户删除，-1:待退款，-2:已退款)
     */
    public void setBookingStatus(Byte bookingStatus) {
        this.bookingStatus = bookingStatus;
    }

    /**
     * 获取 创建时间 字段:booking_info.createTime
     *
     * @return booking_info.createTime, 创建时间
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:booking_info.createTime
     *
     * @param createTime the value for booking_info.createTime, 创建时间
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
}