package cuit.hotel.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class CommentInfo implements Serializable {
    /**
     * 订单号
     * 表字段 : comment_info.bookingID
     */
    private Integer bookingID;

    /**
     * 用户id
     * 表字段 : comment_info.userID
     */
    private Integer userID;

    /**
     * 酒店ID
     * 表字段 : comment_info.hotelID
     */
    private Integer hotelID;

    /**
     * 评分（1-5）
     * 表字段 : comment_info.score
     */
    private Double score;

    /**
     * 评价内容
     * 表字段 : comment_info.content
     */
    private String content;

    /**
     * 回复内容，默认无
     * 表字段 : comment_info.reply
     */
    private String reply;

    /**
     * 评价状态，0:待审核，1:已审核
     * 表字段 : comment_info.commentStatus
     */
    private Byte commentStatus;

    /**
     * 评价创建时间
     * 表字段 : comment_info.createTime
     */
    private String createTime;

    /**
     * 用户名
     * 表字段 : comment_info.userName
     */
    private String userName;

    /**
     * 房型名
     * 表字段 : comment_info.roomTypeName
     */
    private String roomTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 订单号 字段:comment_info.bookingID
     *
     * @return comment_info.bookingID, 订单号
     */
    public Integer getBookingID() {
        return bookingID;
    }

    /**
     * 设置 订单号 字段:comment_info.bookingID
     *
     * @param bookingID the value for comment_info.bookingID, 订单号
     */
    public void setBookingID(Integer bookingID) {
        this.bookingID = bookingID;
    }

    /**
     * 获取 用户id 字段:comment_info.userID
     *
     * @return comment_info.userID, 用户id
     */
    public Integer getUserID() {
        return userID;
    }

    /**
     * 设置 用户id 字段:comment_info.userID
     *
     * @param userID the value for comment_info.userID, 用户id
     */
    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    /**
     * 获取 酒店ID 字段:comment_info.hotelID
     *
     * @return comment_info.hotelID, 酒店ID
     */
    public Integer getHotelID() {
        return hotelID;
    }

    /**
     * 设置 酒店ID 字段:comment_info.hotelID
     *
     * @param hotelID the value for comment_info.hotelID, 酒店ID
     */
    public void setHotelID(Integer hotelID) {
        this.hotelID = hotelID;
    }

    /**
     * 获取 评分（1-5） 字段:comment_info.score
     *
     * @return comment_info.score, 评分（1-5）
     */
    public Double getScore() {
        return score;
    }

    /**
     * 设置 评分（1-5） 字段:comment_info.score
     *
     * @param score the value for comment_info.score, 评分（1-5）
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * 获取 评价内容 字段:comment_info.content
     *
     * @return comment_info.content, 评价内容
     */
    public String getContent() {
        return content;
    }

    /**
     * 设置 评价内容 字段:comment_info.content
     *
     * @param content the value for comment_info.content, 评价内容
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * 获取 回复内容，默认无 字段:comment_info.reply
     *
     * @return comment_info.reply, 回复内容，默认无
     */
    public String getReply() {
        return reply;
    }

    /**
     * 设置 回复内容，默认无 字段:comment_info.reply
     *
     * @param reply the value for comment_info.reply, 回复内容，默认无
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * 获取 评论状态，0:待审核，1:已审核 字段:comment_info.commentStatus
     *
     * @return comment_info.commentStatus, 评论状态，0:待审核，1:已审核
     */
    public Byte getCommentStatus() {
        return commentStatus;
    }

    /**
     * 设置 评论状态，0:待审核，1:已审核 字段:comment_info.commentStatus
     *
     * @param commentStatus the value for comment_info.commentStatus, 评论状态，0:待审核，1:已审核
     */
    public void setCommentStatus(Byte commentStatus) {
        this.commentStatus = commentStatus;
    }

    /**
     * 获取 评论创建时间 字段:comment_info.createTime
     *
     * @return comment_info.createTime, 评论创建时间
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * 设置 评论创建时间 字段:comment_info.createTime
     *
     * @param createTime the value for comment_info.createTime, 评论创建时间
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 用户名 字段:comment_info.userName
     *
     * @return comment_info.userName, 用户名
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 设置 用户名 字段:comment_info.userName
     *
     * @param userName the value for comment_info.userName, 用户名
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * 获取 房型名 字段:comment_info.roomTypeName
     *
     * @return comment_info.roomTypeName, 房型名
     */
    public String getRoomTypeName() {
        return roomTypeName;
    }

    /**
     * 设置 房型名 字段:comment_info.roomTypeName
     *
     * @param roomTypeName the value for comment_info.roomTypeName, 房型名
     */
    public void setRoomTypeName(String roomTypeName) {
        this.roomTypeName = roomTypeName == null ? null : roomTypeName.trim();
    }
}