package cuit.hotel.entity;

import java.io.Serializable;

public class HotelInfo implements Serializable {
    /**
     * 
     * 表字段 : hotel_info.hotelID
     */
    private Integer hotelID;

    /**
     * 酒店名称
     * 表字段 : hotel_info.hotelName
     */
    private String hotelName;

    /**
     * 酒店所在城市
     * 表字段 : hotel_info.city
     */
    private String city;

    /**
     * 酒店详细地址
     * 表字段 : hotel_info.address
     */
    private String address;

    /**
     * 酒店联系电话
     * 表字段 : hotel_info.phone
     */
    private String phone;

    /**
     * 酒店综合评分(0-5)，默认为5
     * 表字段 : hotel_info.score
     */
    private Double score;

    /**
     * 起始价
     * 表字段 : hotel_info.startingPrice
     */
    private Double startingPrice;


    /**
     * 酒店图片
     * 表字段 : hotel_info.imgs
     */
    private String imgs;

    /**
     * 酒店简介
     * 表字段 : hotel_info.introduction
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:hotel_info.hotelID
     *
     * @return hotel_info.hotelID, 
     */
    public Integer getHotelID() {
        return hotelID;
    }

    /**
     * 设置  字段:hotel_info.hotelID
     *
     * @param hotelID the value for hotel_info.hotelID, 
     */
    public void setHotelID(Integer hotelID) {
        this.hotelID = hotelID;
    }

    /**
     * 获取 酒店名称 字段:hotel_info.hotelName
     *
     * @return hotel_info.hotelName, 酒店名称
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * 设置 酒店名称 字段:hotel_info.hotelName
     *
     * @param hotelName the value for hotel_info.hotelName, 酒店名称
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName == null ? null : hotelName.trim();
    }

    /**
     * 获取 酒店所在城市 字段:hotel_info.city
     *
     * @return hotel_info.city, 酒店所在城市
     */
    public String getCity() {
        return city;
    }

    /**
     * 设置 酒店所在城市 字段:hotel_info.city
     *
     * @param city the value for hotel_info.city, 酒店所在城市
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * 获取 酒店详细地址 字段:hotel_info.address
     *
     * @return hotel_info.address, 酒店详细地址
     */
    public String getAddress() {
        return address;
    }

    /**
     * 设置 酒店详细地址 字段:hotel_info.address
     *
     * @param address the value for hotel_info.address, 酒店详细地址
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * 获取 酒店联系电话 字段:hotel_info.phone
     *
     * @return hotel_info.phone, 酒店联系电话
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置 酒店联系电话 字段:hotel_info.phone
     *
     * @param phone the value for hotel_info.phone, 酒店联系电话
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 获取 酒店综合评分(0-5)，默认为5 字段:hotel_info.score
     *
     * @return hotel_info.score, 酒店综合评分(0-5)，默认为5
     */
    public Double getScore() {
        return score;
    }

    /**
     * 设置 酒店综合评分(0-5)，默认为5 字段:hotel_info.score
     *
     * @param score the value for hotel_info.score, 酒店综合评分(0-5)，默认为5
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * 获取 起始价 字段:hotel_info.startingPrice
     *
     * @return hotel_info.startingPrice, 起始价
     */
    public Double getStartingPrice() {
        return startingPrice;
    }

    /**
     * 设置 起始价 字段:hotel_info.startingPrice
     *
     * @param startingPrice the value for hotel_info.startingPrice, 起始价
     */
    public void setStartingPrice(Double startingPrice) {
        this.startingPrice = startingPrice;
    }

    /**
     * 获取 酒店图片 字段:hotel_info.imgs
     *
     * @return hotel_info.imgs, 酒店图片
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * 设置 酒店图片 字段:hotel_info.imgs
     *
     * @param imgs the value for hotel_info.imgs, 酒店图片
     */
    public void setImgs(String imgs) {
        this.imgs = imgs == null ? null : imgs.trim();
    }

    /**
     * 获取 酒店简介 字段:hotel_info.introduction
     *
     * @return hotel_info.introduction, 酒店简介
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * 设置 酒店简介 字段:hotel_info.introduction
     *
     * @param introduction the value for hotel_info.introduction, 酒店简介
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}