package cuit.hotel.entity;


import java.io.Serializable;

public class HotelCollection implements Serializable {
    /**
     * 用户id
     * 表字段 : hotel_collection.userID
     */
    private Integer userID;

    /**
     * 酒店id
     * 表字段 : hotel_collection.hotelID
     */
    private Integer hotelID;

    /**
     * 酒店名称
     * 表字段 : hotel_collection.hotelName
     */
    private String hotelName;

    /**
     * 酒店预订起始价
     * 表字段 : hotel_collection.startingPrice
     */
    private Double startingPrice;

    /**
     * 所在城市
     * 表字段 : hotel_collection.city
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_collection
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 用户id 字段:hotel_collection.userID
     *
     * @return hotel_collection.userID, 用户id
     */
    public Integer getUserID() {
        return userID;
    }

    /**
     * 设置 用户id 字段:hotel_collection.userID
     *
     * @param userID the value for hotel_collection.userID, 用户id
     */
    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    /**
     * 获取 酒店id 字段:hotel_collection.hotelID
     *
     * @return hotel_collection.hotelID, 酒店id
     */
    public Integer getHotelID() {
        return hotelID;
    }

    /**
     * 设置 酒店id 字段:hotel_collection.hotelID
     *
     * @param hotelID the value for hotel_collection.hotelID, 酒店id
     */
    public void setHotelID(Integer hotelID) {
        this.hotelID = hotelID;
    }

    /**
     * 获取 酒店名称 字段:hotel_collection.hotelName
     *
     * @return hotel_collection.hotelName, 酒店名称
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * 设置 酒店名称 字段:hotel_collection.hotelName
     *
     * @param hotelName the value for hotel_collection.hotelName, 酒店名称
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName == null ? null : hotelName.trim();
    }

    /**
     * 获取 酒店预订起始价 字段:hotel_collection.startingPrice
     *
     * @return hotel_collection.startingPrice, 酒店预订起始价
     */
    public Double getStartingPrice() {
        return startingPrice;
    }

    /**
     * 设置 酒店预订起始价 字段:hotel_collection.startingPrice
     *
     * @param startingPrice the value for hotel_collection.startingPrice, 酒店预订起始价
     */
    public void setStartingPrice(Double startingPrice) {
        this.startingPrice = startingPrice;
    }

    /**
     * 获取 所在城市 字段:hotel_collection.city
     *
     * @return hotel_collection.city, 所在城市
     */
    public String getCity() {
        return city;
    }

    /**
     * 设置 所在城市 字段:hotel_collection.city
     *
     * @param city the value for hotel_collection.city, 所在城市
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}