package cuit.hotel.entity;

import java.io.Serializable;

public class RoleInfo implements Serializable {
    /**
     * 角色编号
     * 表字段 : role_info.roleID
     */
    private Integer roleID;

    /**
     * 角色名称
     * 表字段 : role_info.roleName
     */
    private String roleName;

    /**
     * 
     * 表字段 : role_info.permission
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 角色编号 字段:role_info.roleID
     *
     * @return role_info.roleID, 角色编号
     */
    public Integer getRoleID() {
        return roleID;
    }

    /**
     * 设置 角色编号 字段:role_info.roleID
     *
     * @param roleID the value for role_info.roleID, 角色编号
     */
    public void setRoleID(Integer roleID) {
        this.roleID = roleID;
    }

    /**
     * 获取 角色名称 字段:role_info.roleName
     *
     * @return role_info.roleName, 角色名称
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * 设置 角色名称 字段:role_info.roleName
     *
     * @param roleName the value for role_info.roleName, 角色名称
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * 获取  字段:role_info.permission
     *
     * @return role_info.permission, 
     */
    public String getPermission() {
        return permission;
    }

    /**
     * 设置  字段:role_info.permission
     *
     * @param permission the value for role_info.permission, 
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }
}